关于OSCD数据加载
Bobholamovic/FCN-CD-PyTorch pull request #5
Opened 2020-07-20 09:49 UTC by Larry-Zheng

哈哈 老哥又是我 
我刚刚在跑你OSCD的这个代码 数据加载很慢 因为每次13张13张地读 
我改了一下 先把数据读好 要用的时候直接索引 
就是空间开销稍微大一点 你看这样改行不

2020-07-22 02:58 UTC, Bobholamovic commented
不错的想法，不过这样似乎会增加700多M的内存开销，你觉得我们是否应该让这个功能成为一个可选项？我的想法是把原先的`cache_labels`也就是`self.cache_on`功能扩展成缓存所有的输入影像对和标签，然后只有在构造函数中指定`cache_labels=True`（为了意义更清晰，可以把这个形参名字换成`cache_on`）时才会启用一次性加载完全部数据的功能。你觉得怎么样？

2020-07-22 03:00 UTC, Bobholamovic requested changes
不错的想法，不过这样似乎会增加700多M的内存开销，你觉得我们是否应该让这个功能成为一个可选项？我的想法是把原先的cache_labels也就是self.cache_on功能扩展成缓存所有的输入影像对和标签，然后只有在构造函数中指定cache_labels=True（为了意义更清晰，可以把这个形参名字换成cache_on）时才会启用一次性加载完全部数据的功能。你觉得怎么样？

2020-07-29 07:44 UTC, Larry-Zheng commented
> 不错的想法，不过这样似乎会增加700多M的内存开销，你觉得我们是否应该让这个功能成为一个可选项？我的想法是把原先的cache_labels也就是self.cache_on功能扩展成缓存所有的输入影像对和标签，然后只有在构造函数中指定cache_labels=True（为了意义更清晰，可以把这个形参名字换成cache_on）时才会启用一次性加载完全部数据的功能。你觉得怎么样？
呃 其实老哥的代码真的封装的好高级 有时候感觉像是底层的包一样 😂 我这里改的话其实也只是实现一下功能 提一下这个想法 老哥如果觉得这个想法不错 就按照你的规范封装嘛~

2020-07-29 07:50 UTC, Larry-Zheng commented
我服务器上跑过 开销的话 我倒是没觉得很大吧  倒是一次次读的话 那是真滴慢😂  不过 这个也确实是OSCD这个特殊的情况 可以弄成一个可选项嘛

2020-07-29 08:32 UTC, Larry-Zheng commented
借这个机会想问一下老哥 我想投稿 但是不清楚变化检测这个方面有啥合适的刊 😂 我研一 没投过稿  所以一点经验也没有 😣  但是我之前跑OSCD还是出了一点效果了 所以想问问老哥 有没有啥合适的刊以及一些投稿时候需要注意的点

2020-07-29 10:51 UTC, merged

2020-07-29 10:56 UTC, Bobholamovic commented
感谢老哥的建议，我又综合了自己的想法改了一版`OSCDDataset`。

我也是研一刚结束哈，也没投过稿，所以这方面没什么建议~

2020-08-03 09:11 UTC, Larry-Zheng commented
哈哈 好的 共勉~&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lin Manhui"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 晚上6:56
收件人: "Bobholamovic/FCN-CD-PyTorch"<FCN-CD-PyTorch@noreply.github.com&gt;; 
抄送: "bittersweet"<519334736@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Bobholamovic/FCN-CD-PyTorch] 关于OSCD数据加载 (#5)





 
感谢老哥的建议，我又综合了自己的想法改了一版OSCDDataset。
 
我也是研一刚结束哈，也没投过稿，所以这方面没什么建议~
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.